plugins {
    alias(libs.plugins.androidApplication) apply false
}

val forcedDependencies = listOf(
    // Room 2.8's schema bundles are kotlinx-serialization @Serializable classes and
    // room-migration requires the 1.8.1 runtime, but the graph also pulled 1.7.3.
    // In 1.7.x, GeneratedSerializer.typeParametersSerializers() is still abstract;
    // from 1.8.0 it has a default implementation, and Room's serializers are
    // compiled against that newer interface without implementing it. Resolving
    // 1.7.3 therefore made MigrationTestHelper die with AbstractMethodError while
    // parsing the exported schema, before any migration could run.
    //
    // Forced to the current release rather than Room's exact floor: a newer
    // runtime stays compatible with serializers generated by older plugin
    // versions, so raising it cannot reintroduce this class of mismatch.
    "org.jetbrains.kotlinx:kotlinx-serialization-core:1.11.0",
    "org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0",
    "com.google.protobuf:protobuf-java:4.35.0",
    "com.google.protobuf:protobuf-kotlin:4.35.0",
    "io.netty:netty-codec:4.2.16.Final",
    "io.netty:netty-codec-http:4.2.16.Final",
    "io.netty:netty-codec-http2:4.2.16.Final",
    "io.netty:netty-common:4.2.16.Final",
    "io.netty:netty-handler:4.2.16.Final",
    "org.bitbucket.b_c:jose4j:0.9.6",
    "org.jdom:jdom2:2.0.6.1",
    "org.apache.commons:commons-lang3:3.20.0",
    "org.apache.httpcomponents:httpclient:4.5.14",
)

gradle.beforeProject {
    buildscript.configurations.configureEach {
        resolutionStrategy.force(*forcedDependencies.toTypedArray())
    }
}

allprojects {
    configurations.configureEach {
        resolutionStrategy.force(*forcedDependencies.toTypedArray())
    }
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
