[package]
name = "letterbox-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "letterbox_core"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
thiserror = "2.0"
mail-parser = "0.11"
uniffi = { version = "0.32", features = ["cli"] }
scraper = "0.27"
url = "2.5"

[build-dependencies]
uniffi = { version = "0.32", features = ["build"] }

[dev-dependencies]
once_cell = "1"

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["user-hooks"]
