// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package org.joefang.letterbox.ffi.proxy

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_letterbox_proxy_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_letterbox_proxy_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "letterbox_proxy"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "letterbox_proxy"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_letterbox_proxy_checksum_func_proxy_check_for_update(
    ): Int
    external fun uniffi_letterbox_proxy_checksum_func_proxy_clear_cache(
    ): Int
    external fun uniffi_letterbox_proxy_checksum_func_proxy_diagnostics(
    ): Int
    external fun uniffi_letterbox_proxy_checksum_func_proxy_fetch_image(
    ): Int
    external fun uniffi_letterbox_proxy_checksum_func_proxy_fetch_images_batch(
    ): Int
    external fun uniffi_letterbox_proxy_checksum_func_proxy_fetch_url(
    ): Int
    external fun uniffi_letterbox_proxy_checksum_func_proxy_init(
    ): Int
    external fun uniffi_letterbox_proxy_checksum_func_proxy_shutdown(
    ): Int
    external fun uniffi_letterbox_proxy_checksum_func_proxy_status(
    ): Int
    external fun ffi_letterbox_proxy_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "letterbox_proxy"))
        
    }
    external fun uniffi_letterbox_proxy_fn_func_proxy_check_for_update(`currentVersion`: RustBuffer.ByValue,`repo`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_letterbox_proxy_fn_func_proxy_clear_cache(uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_letterbox_proxy_fn_func_proxy_diagnostics(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_letterbox_proxy_fn_func_proxy_fetch_image(`url`: RustBuffer.ByValue,`headers`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_letterbox_proxy_fn_func_proxy_fetch_images_batch(`urls`: RustBuffer.ByValue,`maxConcurrent`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_letterbox_proxy_fn_func_proxy_fetch_url(`url`: RustBuffer.ByValue,`headers`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_letterbox_proxy_fn_func_proxy_init(`storagePath`: RustBuffer.ByValue,`maxCacheSize`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_letterbox_proxy_fn_func_proxy_shutdown(uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_letterbox_proxy_fn_func_proxy_status(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_letterbox_proxy_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_letterbox_proxy_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_letterbox_proxy_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_letterbox_proxy_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_letterbox_proxy_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_letterbox_proxy_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_letterbox_proxy_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_letterbox_proxy_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_letterbox_proxy_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_letterbox_proxy_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_letterbox_proxy_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_letterbox_proxy_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_letterbox_proxy_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_letterbox_proxy_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_letterbox_proxy_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_letterbox_proxy_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_letterbox_proxy_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_letterbox_proxy_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_letterbox_proxy_checksum_func_proxy_check_for_update() != 8783) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_letterbox_proxy_checksum_func_proxy_clear_cache() != 62065) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_letterbox_proxy_checksum_func_proxy_diagnostics() != 157) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_letterbox_proxy_checksum_func_proxy_fetch_image() != 63800) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_letterbox_proxy_checksum_func_proxy_fetch_images_batch() != 3727) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_letterbox_proxy_checksum_func_proxy_fetch_url() != 15037) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_letterbox_proxy_checksum_func_proxy_init() != 3960) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_letterbox_proxy_checksum_func_proxy_shutdown() != 19042) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_letterbox_proxy_checksum_func_proxy_status() != 33270) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    fun lift(value: Int): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2UL

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterFloat: FfiConverter<Float, Float> {
    override fun lift(value: Float): Float {
        return value
    }

    override fun read(buf: ByteBuffer): Float {
        return buf.getFloat()
    }

    override fun lower(value: Float): Float {
        return value
    }

    override fun allocationSize(value: Float) = 4UL

    override fun write(value: Float, buf: ByteBuffer) {
        buf.putFloat(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



/**
 * Result of a batch image fetch operation.
 */
data class BatchImageResult (
    /**
     * URL that was requested.
     */
    var `url`: kotlin.String
    , 
    /**
     * Whether the fetch was successful.
     */
    var `success`: kotlin.Boolean
    , 
    /**
     * Image response if successful.
     */
    var `response`: ImageResponse?
    , 
    /**
     * Error message if failed.
     */
    var `error`: kotlin.String?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBatchImageResult: FfiConverterRustBuffer<BatchImageResult> {
    override fun read(buf: ByteBuffer): BatchImageResult {
        return BatchImageResult(
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalTypeImageResponse.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: BatchImageResult) = (
            FfiConverterString.allocationSize(value.`url`) +
            FfiConverterBoolean.allocationSize(value.`success`) +
            FfiConverterOptionalTypeImageResponse.allocationSize(value.`response`) +
            FfiConverterOptionalString.allocationSize(value.`error`)
    )

    override fun write(value: BatchImageResult, buf: ByteBuffer) {
            FfiConverterString.write(value.`url`, buf)
            FfiConverterBoolean.write(value.`success`, buf)
            FfiConverterOptionalTypeImageResponse.write(value.`response`, buf)
            FfiConverterOptionalString.write(value.`error`, buf)
    }
}



/**
 * Result of a generic tunnelled fetch (non-image content).
 */
data class HttpFetchResponse (
    /**
     * HTTP status code of the final response.
     */
    var `status`: kotlin.UShort
    , 
    /**
     * Normalised MIME type.
     */
    var `mimeType`: kotlin.String
    , 
    /**
     * Raw response body.
     */
    var `data`: kotlin.ByteArray
    , 
    /**
     * Final URL after redirects.
     */
    var `finalUrl`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHttpFetchResponse: FfiConverterRustBuffer<HttpFetchResponse> {
    override fun read(buf: ByteBuffer): HttpFetchResponse {
        return HttpFetchResponse(
            FfiConverterUShort.read(buf),
            FfiConverterString.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: HttpFetchResponse) = (
            FfiConverterUShort.allocationSize(value.`status`) +
            FfiConverterString.allocationSize(value.`mimeType`) +
            FfiConverterByteArray.allocationSize(value.`data`) +
            FfiConverterString.allocationSize(value.`finalUrl`)
    )

    override fun write(value: HttpFetchResponse, buf: ByteBuffer) {
            FfiConverterUShort.write(value.`status`, buf)
            FfiConverterString.write(value.`mimeType`, buf)
            FfiConverterByteArray.write(value.`data`, buf)
            FfiConverterString.write(value.`finalUrl`, buf)
    }
}



/**
 * Result of a successful image fetch operation.
 */
data class ImageResponse (
    /**
     * MIME type of the image (e.g., "image/png", "image/svg+xml").
     */
    var `mimeType`: kotlin.String
    , 
    /**
     * Raw image bytes.
     */
    var `data`: kotlin.ByteArray
    , 
    /**
     * Whether this response was served from cache.
     */
    var `fromCache`: kotlin.Boolean
    , 
    /**
     * Final URL after redirects (if any).
     */
    var `finalUrl`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeImageResponse: FfiConverterRustBuffer<ImageResponse> {
    override fun read(buf: ByteBuffer): ImageResponse {
        return ImageResponse(
            FfiConverterString.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: ImageResponse) = (
            FfiConverterString.allocationSize(value.`mimeType`) +
            FfiConverterByteArray.allocationSize(value.`data`) +
            FfiConverterBoolean.allocationSize(value.`fromCache`) +
            FfiConverterString.allocationSize(value.`finalUrl`)
    )

    override fun write(value: ImageResponse, buf: ByteBuffer) {
            FfiConverterString.write(value.`mimeType`, buf)
            FfiConverterByteArray.write(value.`data`, buf)
            FfiConverterBoolean.write(value.`fromCache`, buf)
            FfiConverterString.write(value.`finalUrl`, buf)
    }
}



/**
 * Status of the image proxy.
 */
data class ProxyStatus (
    /**
     * Whether the proxy is initialized and ready.
     */
    var `ready`: kotlin.Boolean
    , 
    /**
     * Whether WARP is enabled on this device.
     */
    var `warpEnabled`: kotlin.Boolean
    , 
    /**
     * Whether the WireGuard tunnel currently has a live session.
     */
    var `tunnelConnected`: kotlin.Boolean
    , 
    /**
     * Current WireGuard endpoint (if provisioned).
     */
    var `endpoint`: kotlin.String?
    , 
    /**
     * Last error message (if any).
     */
    var `lastError`: kotlin.String?
    , 
    /**
     * Number of cached images.
     */
    var `cacheSize`: kotlin.UInt
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeProxyStatus: FfiConverterRustBuffer<ProxyStatus> {
    override fun read(buf: ByteBuffer): ProxyStatus {
        return ProxyStatus(
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: ProxyStatus) = (
            FfiConverterBoolean.allocationSize(value.`ready`) +
            FfiConverterBoolean.allocationSize(value.`warpEnabled`) +
            FfiConverterBoolean.allocationSize(value.`tunnelConnected`) +
            FfiConverterOptionalString.allocationSize(value.`endpoint`) +
            FfiConverterOptionalString.allocationSize(value.`lastError`) +
            FfiConverterUInt.allocationSize(value.`cacheSize`)
    )

    override fun write(value: ProxyStatus, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`ready`, buf)
            FfiConverterBoolean.write(value.`warpEnabled`, buf)
            FfiConverterBoolean.write(value.`tunnelConnected`, buf)
            FfiConverterOptionalString.write(value.`endpoint`, buf)
            FfiConverterOptionalString.write(value.`lastError`, buf)
            FfiConverterUInt.write(value.`cacheSize`, buf)
    }
}



/**
 * Result of an in-app update check.
 */
data class UpdateResult (
    /**
     * Whether a newer release is available.
     */
    var `updateAvailable`: kotlin.Boolean
    , 
    /**
     * Running version as reported by the caller.
     */
    var `currentVersion`: kotlin.String
    , 
    /**
     * Latest release version (no leading `v`).
     */
    var `latestVersion`: kotlin.String
    , 
    /**
     * Latest release git tag.
     */
    var `latestTag`: kotlin.String
    , 
    /**
     * Release notes.
     */
    var `changelog`: kotlin.String
    , 
    /**
     * Release page URL.
     */
    var `releaseUrl`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeUpdateResult: FfiConverterRustBuffer<UpdateResult> {
    override fun read(buf: ByteBuffer): UpdateResult {
        return UpdateResult(
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: UpdateResult) = (
            FfiConverterBoolean.allocationSize(value.`updateAvailable`) +
            FfiConverterString.allocationSize(value.`currentVersion`) +
            FfiConverterString.allocationSize(value.`latestVersion`) +
            FfiConverterString.allocationSize(value.`latestTag`) +
            FfiConverterString.allocationSize(value.`changelog`) +
            FfiConverterString.allocationSize(value.`releaseUrl`)
    )

    override fun write(value: UpdateResult, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`updateAvailable`, buf)
            FfiConverterString.write(value.`currentVersion`, buf)
            FfiConverterString.write(value.`latestVersion`, buf)
            FfiConverterString.write(value.`latestTag`, buf)
            FfiConverterString.write(value.`changelog`, buf)
            FfiConverterString.write(value.`releaseUrl`, buf)
    }
}



/**
 * Full WireGuard/WARP diagnostics for the in-app debug screen.
 *
 * This intentionally includes the private key so power users can fully inspect
 * and reproduce the tunnel; the Android UI hides it behind an explicit reveal.
 */
data class WarpDiagnostics (
    /**
     * `"connected"` or `"disconnected"`.
     */
    var `connectionState`: kotlin.String
    , 
    /**
     * WireGuard private key (base64).
     */
    var `privateKey`: kotlin.String
    , 
    /**
     * Derived WireGuard public key (base64).
     */
    var `publicKey`: kotlin.String
    , 
    /**
     * WARP peer public key (base64).
     */
    var `peerPublicKey`: kotlin.String
    , 
    /**
     * Endpoint hostname.
     */
    var `endpointHost`: kotlin.String
    , 
    /**
     * Endpoint IPv4 address.
     */
    var `endpointIpv4`: kotlin.String
    , 
    /**
     * Endpoint UDP port.
     */
    var `endpointPort`: kotlin.UShort
    , 
    /**
     * Local tunnel IPv4 address.
     */
    var `localAddressIpv4`: kotlin.String
    , 
    /**
     * Whether WARP is enabled on the account.
     */
    var `warpEnabled`: kotlin.Boolean
    , 
    /**
     * Account type (e.g. `free`).
     */
    var `accountType`: kotlin.String
    , 
    /**
     * Cloudflare account/device identifier.
     */
    var `accountId`: kotlin.String
    , 
    /**
     * Seconds since the last completed handshake, if any.
     */
    var `lastHandshakeSecs`: kotlin.ULong?
    , 
    /**
     * Plaintext bytes transmitted into the tunnel.
     */
    var `txBytes`: kotlin.ULong
    , 
    /**
     * Plaintext bytes received from the tunnel.
     */
    var `rxBytes`: kotlin.ULong
    , 
    /**
     * Estimated packet loss in `[0.0, 1.0]`.
     */
    var `estimatedLoss`: kotlin.Float
    , 
    /**
     * Estimated round-trip time in milliseconds, if measured.
     */
    var `rttMs`: kotlin.UInt?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeWarpDiagnostics: FfiConverterRustBuffer<WarpDiagnostics> {
    override fun read(buf: ByteBuffer): WarpDiagnostics {
        return WarpDiagnostics(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterOptionalUInt.read(buf),
        )
    }

    override fun allocationSize(value: WarpDiagnostics) = (
            FfiConverterString.allocationSize(value.`connectionState`) +
            FfiConverterString.allocationSize(value.`privateKey`) +
            FfiConverterString.allocationSize(value.`publicKey`) +
            FfiConverterString.allocationSize(value.`peerPublicKey`) +
            FfiConverterString.allocationSize(value.`endpointHost`) +
            FfiConverterString.allocationSize(value.`endpointIpv4`) +
            FfiConverterUShort.allocationSize(value.`endpointPort`) +
            FfiConverterString.allocationSize(value.`localAddressIpv4`) +
            FfiConverterBoolean.allocationSize(value.`warpEnabled`) +
            FfiConverterString.allocationSize(value.`accountType`) +
            FfiConverterString.allocationSize(value.`accountId`) +
            FfiConverterOptionalULong.allocationSize(value.`lastHandshakeSecs`) +
            FfiConverterULong.allocationSize(value.`txBytes`) +
            FfiConverterULong.allocationSize(value.`rxBytes`) +
            FfiConverterFloat.allocationSize(value.`estimatedLoss`) +
            FfiConverterOptionalUInt.allocationSize(value.`rttMs`)
    )

    override fun write(value: WarpDiagnostics, buf: ByteBuffer) {
            FfiConverterString.write(value.`connectionState`, buf)
            FfiConverterString.write(value.`privateKey`, buf)
            FfiConverterString.write(value.`publicKey`, buf)
            FfiConverterString.write(value.`peerPublicKey`, buf)
            FfiConverterString.write(value.`endpointHost`, buf)
            FfiConverterString.write(value.`endpointIpv4`, buf)
            FfiConverterUShort.write(value.`endpointPort`, buf)
            FfiConverterString.write(value.`localAddressIpv4`, buf)
            FfiConverterBoolean.write(value.`warpEnabled`, buf)
            FfiConverterString.write(value.`accountType`, buf)
            FfiConverterString.write(value.`accountId`, buf)
            FfiConverterOptionalULong.write(value.`lastHandshakeSecs`, buf)
            FfiConverterULong.write(value.`txBytes`, buf)
            FfiConverterULong.write(value.`rxBytes`, buf)
            FfiConverterFloat.write(value.`estimatedLoss`, buf)
            FfiConverterOptionalUInt.write(value.`rttMs`, buf)
    }
}





/**
 * Errors that can occur during proxy operations.
 */
sealed class ProxyException: kotlin.Exception() {
    
    /**
     * The proxy has not been initialized. Call `proxy_init()` first.
     */
    class NotInitialized(
        ) : ProxyException() {
        override val message
            get() = ""
    }
    
    /**
     * Failed to initialize the proxy.
     */
    class InitializationFailed(
        
        /**
         * Detailed error message
         */
        val `details`: kotlin.String
        ) : ProxyException() {
        override val message
            get() = "details=${ `details` }"
    }
    
    /**
     * Failed to provision WARP credentials.
     */
    class ProvisioningFailed(
        
        /**
         * Detailed error message
         */
        val `details`: kotlin.String
        ) : ProxyException() {
        override val message
            get() = "details=${ `details` }"
    }
    
    /**
     * Failed to establish WireGuard tunnel.
     */
    class TunnelException(
        
        /**
         * Detailed error message
         */
        val `details`: kotlin.String
        ) : ProxyException() {
        override val message
            get() = "details=${ `details` }"
    }
    
    /**
     * Invalid URL provided.
     */
    class InvalidUrl(
        
        /**
         * The invalid URL
         */
        val `url`: kotlin.String, 
        
        /**
         * Detailed error message
         */
        val `details`: kotlin.String
        ) : ProxyException() {
        override val message
            get() = "url=${ `url` }, details=${ `details` }"
    }
    
    /**
     * HTTP request failed.
     */
    class HttpException(
        
        /**
         * HTTP status code (0 if connection failed)
         */
        val `statusCode`: kotlin.UShort, 
        
        /**
         * Detailed error message
         */
        val `details`: kotlin.String
        ) : ProxyException() {
        override val message
            get() = "statusCode=${ `statusCode` }, details=${ `details` }"
    }
    
    /**
     * The response content type is not an image.
     */
    class InvalidContentType(
        
        /**
         * The actual content type received
         */
        val `contentType`: kotlin.String
        ) : ProxyException() {
        override val message
            get() = "contentType=${ `contentType` }"
    }
    
    /**
     * The response is too large.
     */
    class ResponseTooLarge(
        
        /**
         * Actual size in bytes
         */
        val `size`: kotlin.ULong, 
        
        /**
         * Maximum allowed size in bytes
         */
        val `maxSize`: kotlin.ULong
        ) : ProxyException() {
        override val message
            get() = "size=${ `size` }, maxSize=${ `maxSize` }"
    }
    
    /**
     * Too many redirects.
     */
    class TooManyRedirects(
        
        /**
         * Number of redirects encountered
         */
        val `count`: kotlin.UInt, 
        
        /**
         * Maximum allowed redirects
         */
        val `maxCount`: kotlin.UInt
        ) : ProxyException() {
        override val message
            get() = "count=${ `count` }, maxCount=${ `maxCount` }"
    }
    
    /**
     * Connection timeout.
     */
    class Timeout(
        
        /**
         * Timeout duration in seconds
         */
        val `seconds`: kotlin.UInt
        ) : ProxyException() {
        override val message
            get() = "seconds=${ `seconds` }"
    }
    
    /**
     * DNS resolution failed.
     */
    class DnsException(
        
        /**
         * The host that failed to resolve
         */
        val `host`: kotlin.String, 
        
        /**
         * Detailed error message
         */
        val `details`: kotlin.String
        ) : ProxyException() {
        override val message
            get() = "host=${ `host` }, details=${ `details` }"
    }
    
    /**
     * TLS handshake failed.
     */
    class TlsException(
        
        /**
         * Detailed error message
         */
        val `details`: kotlin.String
        ) : ProxyException() {
        override val message
            get() = "details=${ `details` }"
    }
    
    /**
     * Failed to read or write configuration.
     */
    class StorageException(
        
        /**
         * Detailed error message
         */
        val `details`: kotlin.String
        ) : ProxyException() {
        override val message
            get() = "details=${ `details` }"
    }
    
    /**
     * WireGuard cryptographic operation failed.
     */
    class CryptoException(
        
        /**
         * Detailed error message
         */
        val `details`: kotlin.String
        ) : ProxyException() {
        override val message
            get() = "details=${ `details` }"
    }
    
    /**
     * Network is unavailable.
     */
    class NetworkUnavailable(
        
        /**
         * Detailed error message
         */
        val `details`: kotlin.String
        ) : ProxyException() {
        override val message
            get() = "details=${ `details` }"
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<ProxyException> {
        override fun lift(error_buf: RustBuffer.ByValue): ProxyException = FfiConverterTypeProxyError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeProxyError : FfiConverterRustBuffer<ProxyException> {
    override fun read(buf: ByteBuffer): ProxyException {
        

        return when(buf.getInt()) {
            1 -> ProxyException.NotInitialized()
            2 -> ProxyException.InitializationFailed(
                FfiConverterString.read(buf),
                )
            3 -> ProxyException.ProvisioningFailed(
                FfiConverterString.read(buf),
                )
            4 -> ProxyException.TunnelException(
                FfiConverterString.read(buf),
                )
            5 -> ProxyException.InvalidUrl(
                FfiConverterString.read(buf),
                FfiConverterString.read(buf),
                )
            6 -> ProxyException.HttpException(
                FfiConverterUShort.read(buf),
                FfiConverterString.read(buf),
                )
            7 -> ProxyException.InvalidContentType(
                FfiConverterString.read(buf),
                )
            8 -> ProxyException.ResponseTooLarge(
                FfiConverterULong.read(buf),
                FfiConverterULong.read(buf),
                )
            9 -> ProxyException.TooManyRedirects(
                FfiConverterUInt.read(buf),
                FfiConverterUInt.read(buf),
                )
            10 -> ProxyException.Timeout(
                FfiConverterUInt.read(buf),
                )
            11 -> ProxyException.DnsException(
                FfiConverterString.read(buf),
                FfiConverterString.read(buf),
                )
            12 -> ProxyException.TlsException(
                FfiConverterString.read(buf),
                )
            13 -> ProxyException.StorageException(
                FfiConverterString.read(buf),
                )
            14 -> ProxyException.CryptoException(
                FfiConverterString.read(buf),
                )
            15 -> ProxyException.NetworkUnavailable(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: ProxyException): ULong {
        return when(value) {
            is ProxyException.NotInitialized -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is ProxyException.InitializationFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`details`)
            )
            is ProxyException.ProvisioningFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`details`)
            )
            is ProxyException.TunnelException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`details`)
            )
            is ProxyException.InvalidUrl -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`url`)
                + FfiConverterString.allocationSize(value.`details`)
            )
            is ProxyException.HttpException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterUShort.allocationSize(value.`statusCode`)
                + FfiConverterString.allocationSize(value.`details`)
            )
            is ProxyException.InvalidContentType -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`contentType`)
            )
            is ProxyException.ResponseTooLarge -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterULong.allocationSize(value.`size`)
                + FfiConverterULong.allocationSize(value.`maxSize`)
            )
            is ProxyException.TooManyRedirects -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterUInt.allocationSize(value.`count`)
                + FfiConverterUInt.allocationSize(value.`maxCount`)
            )
            is ProxyException.Timeout -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterUInt.allocationSize(value.`seconds`)
            )
            is ProxyException.DnsException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`host`)
                + FfiConverterString.allocationSize(value.`details`)
            )
            is ProxyException.TlsException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`details`)
            )
            is ProxyException.StorageException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`details`)
            )
            is ProxyException.CryptoException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`details`)
            )
            is ProxyException.NetworkUnavailable -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`details`)
            )
        }
    }

    override fun write(value: ProxyException, buf: ByteBuffer) {
        when(value) {
            is ProxyException.NotInitialized -> {
                buf.putInt(1)
                Unit
            }
            is ProxyException.InitializationFailed -> {
                buf.putInt(2)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
            is ProxyException.ProvisioningFailed -> {
                buf.putInt(3)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
            is ProxyException.TunnelException -> {
                buf.putInt(4)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
            is ProxyException.InvalidUrl -> {
                buf.putInt(5)
                FfiConverterString.write(value.`url`, buf)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
            is ProxyException.HttpException -> {
                buf.putInt(6)
                FfiConverterUShort.write(value.`statusCode`, buf)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
            is ProxyException.InvalidContentType -> {
                buf.putInt(7)
                FfiConverterString.write(value.`contentType`, buf)
                Unit
            }
            is ProxyException.ResponseTooLarge -> {
                buf.putInt(8)
                FfiConverterULong.write(value.`size`, buf)
                FfiConverterULong.write(value.`maxSize`, buf)
                Unit
            }
            is ProxyException.TooManyRedirects -> {
                buf.putInt(9)
                FfiConverterUInt.write(value.`count`, buf)
                FfiConverterUInt.write(value.`maxCount`, buf)
                Unit
            }
            is ProxyException.Timeout -> {
                buf.putInt(10)
                FfiConverterUInt.write(value.`seconds`, buf)
                Unit
            }
            is ProxyException.DnsException -> {
                buf.putInt(11)
                FfiConverterString.write(value.`host`, buf)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
            is ProxyException.TlsException -> {
                buf.putInt(12)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
            is ProxyException.StorageException -> {
                buf.putInt(13)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
            is ProxyException.CryptoException -> {
                buf.putInt(14)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
            is ProxyException.NetworkUnavailable -> {
                buf.putInt(15)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalUInt: FfiConverterRustBuffer<kotlin.UInt?> {
    override fun read(buf: ByteBuffer): kotlin.UInt? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterUInt.read(buf)
    }

    override fun allocationSize(value: kotlin.UInt?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterUInt.allocationSize(value)
        }
    }

    override fun write(value: kotlin.UInt?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterUInt.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalULong: FfiConverterRustBuffer<kotlin.ULong?> {
    override fun read(buf: ByteBuffer): kotlin.ULong? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterULong.read(buf)
    }

    override fun allocationSize(value: kotlin.ULong?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterULong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.ULong?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterULong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeImageResponse: FfiConverterRustBuffer<ImageResponse?> {
    override fun read(buf: ByteBuffer): ImageResponse? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeImageResponse.read(buf)
    }

    override fun allocationSize(value: ImageResponse?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeImageResponse.allocationSize(value)
        }
    }

    override fun write(value: ImageResponse?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeImageResponse.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalMapStringString: FfiConverterRustBuffer<Map<kotlin.String, kotlin.String>?> {
    override fun read(buf: ByteBuffer): Map<kotlin.String, kotlin.String>? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterMapStringString.read(buf)
    }

    override fun allocationSize(value: Map<kotlin.String, kotlin.String>?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterMapStringString.allocationSize(value)
        }
    }

    override fun write(value: Map<kotlin.String, kotlin.String>?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterMapStringString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeBatchImageResult: FfiConverterRustBuffer<List<BatchImageResult>> {
    override fun read(buf: ByteBuffer): List<BatchImageResult> {
        val len = buf.getInt()
        return List<BatchImageResult>(len) {
            FfiConverterTypeBatchImageResult.read(buf)
        }
    }

    override fun allocationSize(value: List<BatchImageResult>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeBatchImageResult.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<BatchImageResult>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeBatchImageResult.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterMapStringString: FfiConverterRustBuffer<Map<kotlin.String, kotlin.String>> {
    override fun read(buf: ByteBuffer): Map<kotlin.String, kotlin.String> {
        val len = buf.getInt()
        return buildMap<kotlin.String, kotlin.String>(len) {
            repeat(len) {
                val k = FfiConverterString.read(buf)
                val v = FfiConverterString.read(buf)
                this[k] = v
            }
        }
    }

    override fun allocationSize(value: Map<kotlin.String, kotlin.String>): ULong {
        val spaceForMapSize = 4UL
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterString.allocationSize(k) +
            FfiConverterString.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<kotlin.String, kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterString.write(k, buf)
            FfiConverterString.write(v, buf)
        }
    }
}
        /**
         * Check for a newer release through the tunnel.
         *
         * Pass the running version (e.g. `"v1.2.3"`); `repo` defaults to the official
         * distribution slug when empty.
         */
    @Throws(ProxyException::class) fun `proxyCheckForUpdate`(`currentVersion`: kotlin.String, `repo`: kotlin.String?): UpdateResult {
            return FfiConverterTypeUpdateResult.lift(
    uniffiRustCallWithError(ProxyException) { _status ->
    UniffiLib.uniffi_letterbox_proxy_fn_func_proxy_check_for_update(
    
        FfiConverterString.lower(`currentVersion`),FfiConverterOptionalString.lower(`repo`),_status)
}
    )
    }
    

        /**
         * Clear the in-memory image cache.
         */
    @Throws(ProxyException::class) fun `proxyClearCache`()
        = 
    uniffiRustCallWithError(ProxyException) { _status ->
    UniffiLib.uniffi_letterbox_proxy_fn_func_proxy_clear_cache(
    
        _status)
}
    
    

        /**
         * Collect full WireGuard/WARP diagnostics, provisioning the tunnel if needed.
         */
    @Throws(ProxyException::class) fun `proxyDiagnostics`(): WarpDiagnostics {
            return FfiConverterTypeWarpDiagnostics.lift(
    uniffiRustCallWithError(ProxyException) { _status ->
    UniffiLib.uniffi_letterbox_proxy_fn_func_proxy_diagnostics(
    
        _status)
}
    )
    }
    

        /**
         * Fetch a single image through the WARP tunnel.
         */
    @Throws(ProxyException::class) fun `proxyFetchImage`(`url`: kotlin.String, `headers`: Map<kotlin.String, kotlin.String>?): ImageResponse {
            return FfiConverterTypeImageResponse.lift(
    uniffiRustCallWithError(ProxyException) { _status ->
    UniffiLib.uniffi_letterbox_proxy_fn_func_proxy_fetch_image(
    
        FfiConverterString.lower(`url`),FfiConverterOptionalMapStringString.lower(`headers`),_status)
}
    )
    }
    

        /**
         * Fetch multiple images through the tunnel.
         *
         * Requests are serviced by the single shared tunnel, so they are processed in
         * order; `max_concurrent` is accepted for API stability but currently advisory.
         */
    @Throws(ProxyException::class) fun `proxyFetchImagesBatch`(`urls`: List<kotlin.String>, `maxConcurrent`: kotlin.UInt): List<BatchImageResult> {
            return FfiConverterSequenceTypeBatchImageResult.lift(
    uniffiRustCallWithError(ProxyException) { _status ->
    UniffiLib.uniffi_letterbox_proxy_fn_func_proxy_fetch_images_batch(
    
        FfiConverterSequenceString.lower(`urls`),FfiConverterUInt.lower(`maxConcurrent`),_status)
}
    )
    }
    

        /**
         * Fetch an arbitrary URL through the tunnel (non-image content allowed).
         */
    @Throws(ProxyException::class) fun `proxyFetchUrl`(`url`: kotlin.String, `headers`: Map<kotlin.String, kotlin.String>?): HttpFetchResponse {
            return FfiConverterTypeHttpFetchResponse.lift(
    uniffiRustCallWithError(ProxyException) { _status ->
    UniffiLib.uniffi_letterbox_proxy_fn_func_proxy_fetch_url(
    
        FfiConverterString.lower(`url`),FfiConverterOptionalMapStringString.lower(`headers`),_status)
}
    )
    }
    

        /**
         * Initialize the image proxy.
         *
         * Loads or creates persisted configuration and prepares the in-memory cache.
         * WARP provisioning and the WireGuard handshake are deferred until the first
         * fetch so initialization stays fast and works offline.
         */
    @Throws(ProxyException::class) fun `proxyInit`(`storagePath`: kotlin.String, `maxCacheSize`: kotlin.UInt)
        = 
    uniffiRustCallWithError(ProxyException) { _status ->
    UniffiLib.uniffi_letterbox_proxy_fn_func_proxy_init(
    
        FfiConverterString.lower(`storagePath`),FfiConverterUInt.lower(`maxCacheSize`),_status)
}
    
    

        /**
         * Shut down the proxy, dropping the tunnel and cache.
         */
    @Throws(ProxyException::class) fun `proxyShutdown`()
        = 
    uniffiRustCallWithError(ProxyException) { _status ->
    UniffiLib.uniffi_letterbox_proxy_fn_func_proxy_shutdown(
    
        _status)
}
    
    

        /**
         * Get the current proxy status.
         */
    @Throws(ProxyException::class) fun `proxyStatus`(): ProxyStatus {
            return FfiConverterTypeProxyStatus.lift(
    uniffiRustCallWithError(ProxyException) { _status ->
    UniffiLib.uniffi_letterbox_proxy_fn_func_proxy_status(
    
        _status)
}
    )
    }
    


